// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:5d8b6477-0930-4a54-a7fc-f484d44b37eb",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_DtuwLjVmP",
    "aws_user_pools_web_client_id": "31horn4s4f6e533g0lm89dohld"
};


export default awsmobile;
