// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:8d5b8897-5d1e-4d56-b317-21eb73b4bdf6",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_y4Nh2Bq2V",
    "aws_user_pools_web_client_id": "47jjnqt5san9isfcmqddl32ajj"
};


export default awsmobile;
